#!/usr/bin/env bash
# Display information of domain and subdomain

# shellcheck disable=SC2086
domain_info() {
    sub_domains=("$@")
    count=$((${#sub_domains[@]}-1))
    i=0
    while [ "$i" -lt "$count" ]
    do
        name="${sub_domains[$i]}.${sub_domains[$count]}"
        ip_addr=$(dig "$name" | tac | awk -v nm=$name '$0 ~ nm {print $5; exit;}')
        record=$(dig "$name" | tac | awk -v nm=$name '$0 ~ nm {print $4; exit;}')
        echo "The subdomain ${sub_domains[$i]} is a $record record and points to $ip_addr"
        ((i++))
    done
}

if [ "$#" -eq 1 ]
then
    sub_domains=("www" "lb-01" "web-01" "web-02")
elif [ "$#" -eq 2 ]
then
    sub_domains=("$2")
fi

domain_info "${sub_domains[@]}" "$1"
