#!/usr/bin/env bash
# Requirements:
    # Install nginx on your web-01
    # Nginx should be listening on port 80
    # When querying Nginx at its root / with a GET request (requesting a page) using curl,
    # it must return a page that contains the string Hello World!
    # As an answer file, write a Bash script that configures a new Ubuntu machine to respect
    # above requirements (this script will be run on the server itself)
    # You can’t use systemctl for restarting nginx

sudo apt update -y
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
