#!/usr/bin/env bash
# Configure the Nginx server so that /redirect_me is redirecting to another page. The redirection must be a '301 Moved Permanently'

sudo apt update -y
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

new_header="\n\tadd_header X-Served-By \$hostname;"
redirect="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
not_found="\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$redirect$new_header$not_found/" /etc/nginx/sites-enabled/default

sudo service nginx restart
