#!/usr/bin/env bash
# Fizz Buzz

counter=1
while [ $counter -le 100 ]
do
	a=$(( counter % 3 ))
	b=$(( counter % 5 ))
	if [ $a -eq 0 ] || [ $b -eq 0 ]
	then
		if [ $a -eq 0 ]
		then
			printf "Fizz"
		fi
		if [ $b -eq 0 ]
		then
			printf "Buzz"
		fi
		printf "\n"
	else
		echo $counter
	fi
	((counter++))
done
