#!/usr/bin/env bash
# prints the string 'Best School' 10 times using a while loop, on the 9th iteration prints 'Hi'

counter=1
while [ $counter -le 10 ]
do
	echo "Best School"
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	fi
	((counter++))
done
