#!/usr/bin/env bash
# prints the string 'Best School' 10 times using a while loop, on the 9th iteration prints 'Hi'

counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
