#!/usr/bin/env bash
# prints numbers from 1 to 20, while iterations 4, 9, 17 print texts

counter=1
while [ $counter -le 20 ]
do
	echo $counter
	case $counter in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((counter++))
done
